export const flashcards = [
  // ================= TARİH =================
  { id: 1, subject: "Tarih", question: "İslamiyet öncesi Türklerde devleti yönetme yetkisinin Tanrı tarafından verildiğine inanılan anlayış nedir?", answer: "Kut Anlayışı" },
  { id: 2, subject: "Tarih", question: "Orhun Abideleri hangi Türk devletine aittir ve kimlerin adına dikilmiştir?", answer: "II. Göktürk (Kutluk) Devleti. Bilge Kağan, Kültigin ve Vezir Tonyukuk adına dikilmiştir." },
  { id: 3, subject: "Tarih", question: "Dünyanın bilinen en uzun destanı olan Manas Destanı hangi Türk devletine aittir?", answer: "Kırgızlar" },
  { id: 4, subject: "Tarih", question: "Anadolu'nun kapılarının Türklere açılmasını sağlayan ve 'Yurt Açan' olarak bilinen savaş hangisidir?", answer: "1071 Malazgirt Savaşı" },
  { id: 5, subject: "Tarih", question: "Anadolu'nun kesin olarak Türk yurdu olmasını sağlayan 'Yurt Tutan' savaş hangisidir?", answer: "1176 Miryokefalon Savaşı" },
  { id: 6, subject: "Tarih", question: "Osmanlı Devleti'nin Rumeli'deki (Avrupa) ilk toprağı neresidir?", answer: "Çimpe Kalesi (Orhan Bey dönemi)" },
  { id: 7, subject: "Tarih", question: "Osmanlı Devleti'nde ilk altın parayı (Sultani) bastıran padişah kimdir?", answer: "Fatih Sultan Mehmet" },
  { id: 8, subject: "Tarih", question: "Osmanlı Devleti'nin Batı'da en geniş sınırlara ulaştığı antlaşma hangisidir?", answer: "Bucaş Antlaşması (1672)" },
  { id: 9, subject: "Tarih", question: "Osmanlı'nın Doğu'da en geniş sınırlara ulaştığı antlaşma hangisidir?", answer: "Ferhat Paşa Antlaşması (1590)" },
  { id: 10, subject: "Tarih", question: "Osmanlı Devleti'nde ilk matbaa hangi dönemde, kim tarafından getirilmiştir?", answer: "Lale Devri'nde, İbrahim Müteferrika ve Sait Efendi tarafından getirilmiştir." },
  { id: 11, subject: "Tarih", question: "Tanzimat Fermanı (Gülhane Hatt-ı Hümayunu) hangi padişah döneminde ilan edilmiştir?", answer: "Abdülmecit (1839)" },
  { id: 12, subject: "Tarih", question: "Mustafa Kemal'in 'Size taarruzu değil, ölmeyi emrediyorum' dediği savaş cephesi hangisidir?", answer: "Çanakkale Cephesi (Conkbayırı)" },
  { id: 13, subject: "Tarih", question: "Mustafa Kemal'e 'Gazi' unvanı ve 'Mareşal' rütbesi hangi savaştan sonra verilmiştir?", answer: "Sakarya Meydan Muharebesi" },
  { id: 14, subject: "Tarih", question: "Milli Mücadele'nin gerekçesi, amacı ve yönteminin ilk kez belirtildiği belge hangisidir?", answer: "Amasya Genelgesi" },
  { id: 15, subject: "Tarih", question: "Temsil Heyeti'nin ilk kez yürütme yetkisini kullandığı olay nedir?", answer: "Ali Fuat Paşa'yı Batı Cephesi Komutanlığına ataması (Sivas Kongresi)." },
  { id: 16, subject: "Tarih", question: "Türkiye Büyük Millet Meclisi'ni (TBMM) tanıyan ilk İslam devleti hangisidir?", answer: "Afganistan" },
  { id: 17, subject: "Tarih", question: "TBMM'yi tanıyan ilk Avrupalı ve İtilaf devleti hangisidir?", answer: "Fransa (1921 Ankara Antlaşması)" },
  { id: 18, subject: "Tarih", question: "Osmanlı Devleti'nin resmen sona ermesine neden olan olay nedir?", answer: "Saltanatın Kaldırılması (1 Kasım 1922)" },
  { id: 19, subject: "Tarih", question: "Cumhuriyet döneminde çok partili hayata geçişin ilk denemesi hangi partinin kurulmasıyla yapılmıştır?", answer: "Terakkiperver Cumhuriyet Fırkası" },
  { id: 20, subject: "Tarih", question: "Türkiye'nin Milletler Cemiyeti'ne (Cemiyet-i Akvam) katıldığı yıl nedir?", answer: "1932" },

  // ================= COĞRAFYA =================
  { id: 21, subject: "Coğrafya", question: "Türkiye'nin en uzun kara sınırı hangi ülke iledir?", answer: "Suriye (911 km)" },
  { id: 22, subject: "Coğrafya", question: "Türkiye'nin en kısa kara sınırı hangi ülke iledir?", answer: "Nahçıvan / Azerbaycan (18 km)" },
  { id: 23, subject: "Coğrafya", question: "Ege Bölgesi'nde dağların denize dik uzanmasının sonucu olarak oluşan, kıyı girinti ve çıkıntısının fazla olduğu kıyı tipi hangisidir?", answer: "Enine Kıyı Tipi" },
  { id: 24, subject: "Coğrafya", question: "Akdeniz Bölgesi'nde kireç taşının erimesiyle oluşan çukurluklara (polye, uvala, dolin) genel olarak ne ad verilir?", answer: "Karstik Şekiller" },
  { id: 25, subject: "Coğrafya", question: "Türkiye'de rüzgar aşındırmasının (erozyon) en şiddetli olduğu bölge neresidir?", answer: "İç Anadolu Bölgesi (Özellikle Karapınar çevresi)" },
  { id: 26, subject: "Coğrafya", question: "Türkiye'nin en büyük gölü olan Van Gölü'nün oluşum türü nedir?", answer: "Volkanik Set Gölü" },
  { id: 27, subject: "Coğrafya", question: "Heyelan olaylarının Türkiye'de en çok görüldüğü mevsim ve bölge neresidir?", answer: "İlkbahar (Kar erimelerinden dolayı) - Karadeniz Bölgesi" },
  { id: 28, subject: "Coğrafya", question: "Ülkemizde çay tarımı, iklim şartları gereği sadece nerede yapılabilmektedir?", answer: "Doğu Karadeniz Bölümü" },
  { id: 29, subject: "Coğrafya", question: "Türkiye'nin ihraç ettiği (dışarı sattığı) madenler arasında en çok gelir getiren ve rezervde dünya birincisi olduğumuz maden hangisidir?", answer: "Mermer ve Bor" },
  { id: 30, subject: "Coğrafya", question: "Sadece Zonguldak çevresinde çıkarılan ve demir-çelik sanayisinde enerji kaynağı olarak kullanılan maden hangisidir?", answer: "Taş Kömürü" },
  { id: 31, subject: "Coğrafya", question: "Jeotermal enerjiden (Sıcak su buharı) elektrik üreten ilk ve en büyük santralimiz nerededir?", answer: "Denizli - Sarayköy" },
  { id: 32, subject: "Coğrafya", question: "Rüzgar enerjisi potansiyelinin en yüksek olduğu ve ilk rüzgar santralinin (Alaçatı) kurulduğu bölge hangisidir?", answer: "Ege Bölgesi" },
  { id: 33, subject: "Coğrafya", question: "Yaz yağışları ile yeşeren uzun çayırların altında oluşan, dünyanın ve Türkiye'nin en verimli toprağı hangisidir?", answer: "Çernezyom (Kara Toprak - Erzurum/Kars)" },
  { id: 34, subject: "Coğrafya", question: "Türkiye'de doğu-batı yönünde gidildikçe sıcaklığın düşmesinin temel nedeni nedir?", answer: "Yükseltinin batıdan doğuya doğru artması." },
  { id: 35, subject: "Coğrafya", question: "Sınır kapılarımızdan hangisi İran'a açılır ve transit ticarette en önemli paya sahiptir?", answer: "Gürbulak Sınır Kapısı (Ağrı)" },

  // ================= VATANDAŞLIK =================
  { id: 36, subject: "Vatandaşlık", question: "1982 Anayasası'na göre Türkiye'de yasama yetkisi kime aittir ve devredilebilir mi?", answer: "Türkiye Büyük Millet Meclisi'ne (TBMM) aittir ve kesinlikle devredilemez." },
  { id: 37, subject: "Vatandaşlık", question: "Milletvekili genel seçimleri ve Cumhurbaşkanlığı seçimleri kaç yılda bir aynı gün yapılır?", answer: "5 yılda bir" },
  { id: 38, subject: "Vatandaşlık", question: "Cumhurbaşkanı seçilebilmek için gerekli olan yaş ve eğitim şartı nedir?", answer: "40 yaşını doldurmuş olmak ve Yükseköğrenim mezunu olmak." },
  { id: 39, subject: "Vatandaşlık", question: "Siyasi partilerin mali denetimini hangi kurum yapar?", answer: "Anayasa Mahkemesi (Sayıştay'dan yardım alarak yapar)" },
  { id: 40, subject: "Vatandaşlık", question: "Kanunların Anayasa'ya şekil ve esas bakımından uygunluğunu denetleyen yüksek mahkeme hangisidir?", answer: "Anayasa Mahkemesi" },
  { id: 41, subject: "Vatandaşlık", question: "Adli yargı kolunun en üst temyiz mercii hangisidir?", answer: "Yargıtay" },
  { id: 42, subject: "Vatandaşlık", question: "İdari yargı kolunun (Devlet kurumlarıyla olan davalar) en üst temyiz mercii hangisidir?", answer: "Danıştay" },
  { id: 43, subject: "Vatandaşlık", question: "Normlar Hiyerarşisi'nin (Hukuk Kuralları Sıralaması) en üstünde ne yer alır?", answer: "Anayasa" },
  { id: 44, subject: "Vatandaşlık", question: "Türkiye'de Olağanüstü Hal (OHAL) ilan etme yetkisi kime aittir ve süresi en fazla ne kadardır?", answer: "Cumhurbaşkanı'na aittir. Süresi en fazla 6 aydır (Uzatma yetkisi TBMM'dedir)." },
  { id: 45, subject: "Vatandaşlık", question: "Haklı bir sebep olmaksızın başkasının malvarlığından zenginleşmeye ne ad verilir?", answer: "Sebepsiz Zenginleşme" },
  { id: 46, subject: "Vatandaşlık", question: "Hukuk kurallarına uyulmaması durumunda devlet gücüyle uygulanan tepkiye ne denir?", answer: "Yaptırım (Müeyyide)" },
  { id: 47, subject: "Vatandaşlık", question: "Türkiye Cumhuriyeti'nde olağan kanun hükmünde kararname (KHK) çıkarma yetkisi 2017 anayasa değişikliğiyle kime geçmiştir?", answer: "KHK'lar kaldırılmış, yerine 'Cumhurbaşkanlığı Kararnamesi' getirilmiştir." },

  // ================= TÜRKÇE (YENİ) =================
  { id: 48, subject: "Türkçe", question: "Yazım Kuralları: 'Önsöz, Ön yargı, Art niyet' kelimeleri bitişik mi yazılır ayrı mı?", answer: "Ayrı yazılır. (Ön söz, ön yargı, art niyet)" },
  { id: 49, subject: "Türkçe", question: "Yazım Kuralları: 'Pek çok', 'Pek az', 'Her şey' kelimeleri nasıl yazılır?", answer: "Her zaman ayrı yazılır." },
  { id: 50, subject: "Türkçe", question: "Ses Olayları: 'Bekliyor' kelimesindeki ses olayı nedir?", answer: "Ünlü Daralması (Bekle-yor -> Bekliyor)" },
  { id: 51, subject: "Türkçe", question: "Ses Olayları: 'Gönlüm' kelimesindeki ses olayı nedir?", answer: "Ünlü Düşmesi (Gönül-üm -> Gönlüm)" },
  { id: 52, subject: "Türkçe", question: "Anlatım Bozukluğu: 'Karşılıklı mektuplaştık.' cümlesindeki bozukluk türü nedir?", answer: "Gereksiz sözcük kullanımı ('Mektuplaşmak' zaten karşılıklı yapılan bir eylemdir)." },

  // ================= MATEMATİK (YENİ) =================
  { id: 53, subject: "Matematik", question: "Formül: 1'den n'e kadar olan ardışık tam sayıların toplam formülü nedir?", answer: "n * (n + 1) / 2" },
  { id: 54, subject: "Matematik", question: "Özdeşlik: İki Kare Farkı formülü (a² - b²) nasıldır?", answer: "(a - b) * (a + b)" },
  { id: 55, subject: "Matematik", question: "Kural: Bir sayının 9'a tam bölünebilmesi için kural nedir?", answer: "Sayının rakamları toplamı 9 veya 9'un katı olmalıdır." },
  { id: 56, subject: "Matematik", question: "Kural: Asal sayılar kümesinin en küçük ve tek çift olan elemanı kaçtır?", answer: "2'dir. (2 dışında çift asal sayı yoktur)." },

  // ================= GÜNCEL & GENEL KÜLTÜR =================
  { id: 57, subject: "Güncel", question: "Birleşmiş Milletler'in (BM) genel merkezi nerededir?", answer: "New York, ABD" },
  { id: 58, subject: "Güncel", question: "NATO'nun (Kuzey Atlantik Antlaşması Örgütü) genel merkezi nerededir?", answer: "Brüksel, Belçika" },
  { id: 59, subject: "Güncel", question: "Avrupa İnsan Hakları Mahkemesi (AİHM) hangi kuruma bağlıdır ve nerededir?", answer: "Avrupa Konseyi'ne bağlıdır. Merkezi Strazburg'dadır (Fransa)." },
  { id: 60, subject: "Güncel", question: "Kuzey Kıbrıs Türk Cumhuriyeti'nin (KKTC) kurucu cumhurbaşkanı kimdir?", answer: "Rauf Raif Denktaş" },
  { id: 61, subject: "Güncel", question: "İstiklal Marşı'mızın şairi Mehmet Akif Ersoy, marşı kime ithaf etmiştir?", answer: "Kahraman Türk Ordusu'na" },
  { id: 62, subject: "Güncel", question: "'Sinekli Bakkal', 'Vurun Kahpeye', 'Ateşten Gömlek' gibi eserlerin yazarı kimdir?", answer: "Halide Edip Adıvar" },
  { id: 63, subject: "Güncel", question: "Türkiye'nin en uzun nehri (ülke sınırları içinde doğup dökülen) hangisidir?", answer: "Kızılırmak" },
  { id: 64, subject: "Güncel", question: "2023 yılında Cumhuriyetimizin 100. yılı şerefine uzaya gönderilen ilk Türk astronotun adı nedir?", answer: "Alper Gezeravcı" }
];
