export const flashcards = [
  // ================= TARİH (35 Kart) =================
  { id: 1, subject: "Tarih", question: "İslamiyet öncesi Türklerde devleti yönetme yetkisinin Tanrı tarafından verildiğine inanılan anlayış nedir?", answer: "Kut Anlayışı" },
  { id: 2, subject: "Tarih", question: "Orhun Abideleri hangi Türk devletine aittir ve kimlerin adına dikilmiştir?", answer: "II. Göktürk (Kutluk) Devleti. Bilge Kağan, Kültigin ve Vezir Tonyukuk adına dikilmiştir." },
  { id: 3, subject: "Tarih", question: "Dünyanın bilinen en uzun destanı olan Manas Destanı hangi Türk devletine aittir?", answer: "Kırgızlar" },
  { id: 4, subject: "Tarih", question: "Anadolu'nun kapılarının Türklere açılmasını sağlayan ve 'Yurt Açan' olarak bilinen savaş hangisidir?", answer: "1071 Malazgirt Savaşı" },
  { id: 5, subject: "Tarih", question: "Anadolu'nun kesin olarak Türk yurdu olmasını sağlayan 'Yurt Tutan' savaş hangisidir?", answer: "1176 Miryokefalon Savaşı" },
  { id: 6, subject: "Tarih", question: "Anadolu Selçuklu Devleti'nin en parlak dönemi hangi sultan zamanında yaşanmıştır?", answer: "I. Alaeddin Keykubat" },
  { id: 7, subject: "Tarih", question: "Osmanlı Devleti'nin Rumeli'deki (Avrupa) ilk toprağı neresidir?", answer: "Çimpe Kalesi (Orhan Bey dönemi)" },
  { id: 8, subject: "Tarih", question: "Osmanlı'nın kuruluş döneminde sosyal yapıyı oluşturan ve 'Ahiler' olarak bilinen zümre hangisidir?", answer: "Ahiyân-ı Rûm (Anadolu Ahileri)" },
  { id: 9, subject: "Tarih", question: "Osmanlı Devleti'nde ilk altın parayı (Sultani) bastıran padişah kimdir?", answer: "Fatih Sultan Mehmet" },
  { id: 10, subject: "Tarih", question: "Osmanlı Devleti'nin Batı'da en geniş sınırlara ulaştığı antlaşma hangisidir?", answer: "Bucaş Antlaşması (1672)" },
  { id: 11, subject: "Tarih", question: "Osmanlı'nın Doğu'da en geniş sınırlara ulaştığı antlaşma hangisidir?", answer: "Ferhat Paşa Antlaşması (1590)" },
  { id: 12, subject: "Tarih", question: "Osmanlı Devleti'nde ilk matbaa hangi dönemde, kim tarafından getirilmiştir?", answer: "Lale Devri'nde, İbrahim Müteferrika ve Sait Efendi tarafından getirilmiştir." },
  { id: 13, subject: "Tarih", question: "Padişahın yetkilerini ilk kez kısıtlayan ve padişah ile ayanlar arasında imzalanan belge nedir?", answer: "Sened-i İttifak (II. Mahmut - 1808)" },
  { id: 14, subject: "Tarih", question: "Tanzimat Fermanı (Gülhane Hatt-ı Hümayunu) hangi padişah döneminde ilan edilmiştir?", answer: "Abdülmecit (1839)" },
  { id: 15, subject: "Tarih", question: "Mustafa Kemal'in tarih sahnesine ilk kez çıktığı ve sömürgeciliğe karşı verdiği ilk mücadele nedir?", answer: "Trablusgarp Savaşı (1911)" },
  { id: 16, subject: "Tarih", question: "Mustafa Kemal'in 'Size taarruzu değil, ölmeyi emrediyorum' dediği savaş cephesi hangisidir?", answer: "Çanakkale Cephesi (Conkbayırı)" },
  { id: 17, subject: "Tarih", question: "Mondros Ateşkes Antlaşması'ndan sonra işgal edilen İLK Osmanlı toprağı neresidir?", answer: "Musul (İngiltere tarafından)" },
  { id: 18, subject: "Tarih", question: "Milli Mücadele'nin gerekçesi, amacı ve yönteminin ilk kez belirtildiği belge hangisidir?", answer: "Amasya Genelgesi" },
  { id: 19, subject: "Tarih", question: "Erzurum Kongresi'nin toplanmasındaki temel amaç nedir?", answer: "Doğu Anadolu'da bir Ermeni devletinin kurulmasını engellemek." },
  { id: 20, subject: "Tarih", question: "Temsil Heyeti'nin ilk kez yürütme yetkisini kullandığı olay nedir?", answer: "Ali Fuat Paşa'yı Batı Cephesi Komutanlığına ataması (Sivas Kongresi)." },
  { id: 21, subject: "Tarih", question: "Türkiye Büyük Millet Meclisi'ni (TBMM) tanıyan ilk İslam devleti hangisidir?", answer: "Afganistan" },
  { id: 22, subject: "Tarih", question: "TBMM'yi tanıyan ilk Avrupalı ve İtilaf devleti hangisidir?", answer: "Fransa (1921 Ankara Antlaşması)" },
  { id: 23, subject: "Tarih", question: "İstiklal Marşı'mız hangi savaştan sonra TBMM tarafından kabul edilmiştir?", answer: "I. İnönü Savaşı (12 Mart 1921)" },
  { id: 24, subject: "Tarih", question: "Mustafa Kemal'e 'Gazi' unvanı ve 'Mareşal' rütbesi hangi savaştan sonra verilmiştir?", answer: "Sakarya Meydan Muharebesi" },
  { id: 25, subject: "Tarih", question: "Lozan Barış Konferansı'nda Türkiye'nin KESİNLİKLE taviz vermediği iki konu nedir?", answer: "Ermeni Yurdu (Toprak bütünlüğü) ve Kapitülasyonlar." },
  { id: 26, subject: "Tarih", question: "Osmanlı Devleti'nin resmen sona ermesine neden olan olay nedir?", answer: "Saltanatın Kaldırılması (1 Kasım 1922)" },
  { id: 27, subject: "Tarih", question: "Cumhuriyet döneminde çok partili hayata geçişin ilk denemesi hangi partinin kurulmasıyla yapılmıştır?", answer: "Terakkiperver Cumhuriyet Fırkası" },
  { id: 28, subject: "Tarih", question: "Türkiye'nin Milletler Cemiyeti'ne (Cemiyet-i Akvam) katıldığı yıl nedir?", answer: "1932" },

  // ================= COĞRAFYA (25 Kart) =================
  { id: 29, subject: "Coğrafya", question: "Türkiye'nin en uzun kara sınırı hangi ülke iledir?", answer: "Suriye (911 km)" },
  { id: 30, subject: "Coğrafya", question: "Türkiye'nin en kısa kara sınırı hangi ülke iledir?", answer: "Nahçıvan / Azerbaycan (18 km)" },
  { id: 31, subject: "Coğrafya", question: "Karadeniz ve Akdeniz'de dağların denize paralel uzanmasının sonucu olarak kıyıda hangi kıyı tipi görülür?", answer: "Boyuna Kıyı Tipi (Kıta sahanlığı dardır, iç kesimlere ulaşım zordur)." },
  { id: 32, subject: "Coğrafya", question: "Ege Bölgesi'nde dağların denize dik uzanmasının sonucu olarak oluşan, kıyı girinti ve çıkıntısının fazla olduğu kıyı tipi hangisidir?", answer: "Enine Kıyı Tipi" },
  { id: 33, subject: "Coğrafya", question: "Akdeniz Bölgesi'nde kireç taşının erimesiyle oluşan çukurluklara (polye, uvala, dolin) genel olarak ne ad verilir?", answer: "Karstik Şekiller" },
  { id: 34, subject: "Coğrafya", question: "Marmara Bölgesi'nin en büyük gölü hangisidir?", answer: "İznik Gölü" },
  { id: 35, subject: "Coğrafya", question: "Türkiye'de rüzgar aşındırmasının (erozyon) en şiddetli olduğu bölge neresidir?", answer: "İç Anadolu Bölgesi (Özellikle Karapınar çevresi)" },
  { id: 36, subject: "Coğrafya", question: "Türkiye'nin en sıcak bölgesi yaz aylarında neresidir ve sebebi nedir?", answer: "Güneydoğu Anadolu'dur. Sebebi; şiddetli karasallık, enlem ve çölden gelen sıcak rüzgarlardır." },
  { id: 37, subject: "Coğrafya", question: "Türkiye'nin en büyük gölü olan Van Gölü'nün oluşum türü nedir?", answer: "Volkanik Set Gölü" },
  { id: 38, subject: "Coğrafya", question: "Heyelan olaylarının Türkiye'de en çok görüldüğü mevsim ve bölge neresidir?", answer: "İlkbahar (Kar erimelerinden dolayı) - Karadeniz Bölgesi" },
  { id: 39, subject: "Coğrafya", question: "Ülkemizde çay tarımı, iklim şartları gereği sadece nerede yapılabilmektedir?", answer: "Doğu Karadeniz Bölümü" },
  { id: 40, subject: "Coğrafya", question: "Tiftik keçisinin (Ankara keçisi) en yoğun yetiştirildiği bölge hangisidir?", answer: "İç Anadolu Bölgesi" },
  { id: 41, subject: "Coğrafya", question: "Türkiye'nin ihraç ettiği (dışarı sattığı) madenler arasında en çok gelir getiren ve rezervde dünya birincisi olduğumuz maden hangisidir?", answer: "Mermer ve Bor" },
  { id: 42, subject: "Coğrafya", question: "Sadece Zonguldak çevresinde çıkarılan ve demir-çelik sanayisinde enerji kaynağı olarak kullanılan maden hangisidir?", answer: "Taş Kömürü" },
  { id: 43, subject: "Coğrafya", question: "Jeotermal enerjiden (Sıcak su buharı) elektrik üreten ilk ve en büyük santralimiz nerededir?", answer: "Denizli - Sarayköy" },
  { id: 44, subject: "Coğrafya", question: "Rüzgar enerjisi potansiyelinin en yüksek olduğu ve ilk rüzgar santralinin (Alaçatı) kurulduğu bölge hangisidir?", answer: "Ege Bölgesi" },
  { id: 45, subject: "Coğrafya", question: "Türkiye'de hangi bölgelerde demiryolu ağı BULUNMAZ?", answer: "Doğu Karadeniz ve Hakkari bölümlerinde dağlık arazi nedeniyle demiryolu yoktur." },
  { id: 46, subject: "Coğrafya", question: "Yaz yağışları ile yeşeren uzun çayırların altında oluşan, dünyanın ve Türkiye'nin en verimli toprağı hangisidir?", answer: "Çernezyom (Kara Toprak - Erzurum/Kars)" },
  { id: 47, subject: "Coğrafya", question: "Sınır kapılarımızdan hangisi İran'a açılır ve transit ticarette en önemli paya sahiptir?", answer: "Gürbulak Sınır Kapısı (Ağrı)" },

  // ================= VATANDAŞLIK (25 Kart) =================
  { id: 48, subject: "Vatandaşlık", question: "1982 Anayasası'na göre Türkiye'de yasama yetkisi kime aittir ve devredilebilir mi?", answer: "Türkiye Büyük Millet Meclisi'ne (TBMM) aittir ve kesinlikle devredilemez." },
  { id: 49, subject: "Vatandaşlık", question: "TBMM'nin toplanabilmesi için gereken 'Toplantı Yeter Sayısı' en az kaçtır?", answer: "Üye tam sayısının en az üçte biri (200 milletvekili) olmalıdır." },
  { id: 50, subject: "Vatandaşlık", question: "Milletvekilliğinin düşme sebepleri nelerdir?", answer: "İstifa, Meclis çalışmalarına 1 ayda 5 birleşim mazeretsiz katılmama, kısıtlanma ve kesin hüküm giyme." },
  { id: 51, subject: "Vatandaşlık", question: "Milletvekili genel seçimleri ve Cumhurbaşkanlığı seçimleri kaç yılda bir aynı gün yapılır?", answer: "5 yılda bir" },
  { id: 52, subject: "Vatandaşlık", question: "Siyasi partilere üye olabilmek için kaç yaşını doldurmuş olmak gerekir?", answer: "18 yaşını doldurmuş olmak gerekir." },
  { id: 53, subject: "Vatandaşlık", question: "Cumhurbaşkanı seçilebilmek için gerekli olan yaş ve eğitim şartı nedir?", answer: "40 yaşını doldurmuş olmak ve Yükseköğrenim mezunu olmak." },
  { id: 54, subject: "Vatandaşlık", question: "Kamu Başdenetçisi (Ombudsman) kime bağlı olarak görev yapar?", answer: "TBMM Başkanlığı'na bağlıdır." },
  { id: 55, subject: "Vatandaşlık", question: "Siyasi partilerin mali denetimini hangi kurum yapar?", answer: "Anayasa Mahkemesi (Sayıştay'dan yardım alarak yapar)" },
  { id: 56, subject: "Vatandaşlık", question: "Kanunların ve CB Kararnamelerinin Anayasa'ya uygunluğunu denetleyen yüksek mahkeme hangisidir?", answer: "Anayasa Mahkemesi" },
  { id: 57, subject: "Vatandaşlık", question: "Adli yargı kolunun en üst temyiz mercii hangisidir?", answer: "Yargıtay" },
  { id: 58, subject: "Vatandaşlık", question: "İdari yargı kolunun (Devlet kurumlarıyla olan davalar) en üst temyiz mercii hangisidir?", answer: "Danıştay" },
  { id: 59, subject: "Vatandaşlık", question: "Yüksek Seçim Kurulu (YSK) kararlarına karşı yargı yolu nasıldır?", answer: "Kapalıdır. YSK kararları kesindir, itiraz edilemez." },
  { id: 60, subject: "Vatandaşlık", question: "Normlar Hiyerarşisi'nin (Hukuk Kuralları Sıralaması) en üstünde ne yer alır?", answer: "Anayasa" },
  { id: 61, subject: "Vatandaşlık", question: "Türkiye'de Olağanüstü Hal (OHAL) ilan etme yetkisi kime aittir ve süresi en fazla ne kadardır?", answer: "Cumhurbaşkanı'na aittir. Süresi en fazla 6 aydır (Uzatma yetkisi TBMM'dedir)." },
  { id: 62, subject: "Vatandaşlık", question: "Haklı bir sebep olmaksızın başkasının malvarlığından zenginleşmeye ne ad verilir?", answer: "Sebepsiz Zenginleşme" },
  { id: 63, subject: "Vatandaşlık", question: "Hukuk kurallarına uyulmaması durumunda devlet gücüyle uygulanan tepkiye ne denir?", answer: "Yaptırım (Müeyyide)" },

  // ================= TÜRKÇE (10 Kart) =================
  { id: 64, subject: "Türkçe", question: "Yazım Kuralları: 'Önsöz, Ön yargı, Art niyet' kelimeleri bitişik mi yazılır ayrı mı?", answer: "Ayrı yazılır. (Ön söz, ön yargı, art niyet)" },
  { id: 65, subject: "Türkçe", question: "Yazım Kuralları: 'Pek çok', 'Pek az', 'Her şey' kelimeleri nasıl yazılır?", answer: "Her zaman ayrı yazılır." },
  { id: 66, subject: "Türkçe", question: "Yazım Kuralları: 'Herhalde' ile 'Her halde' arasındaki fark nedir?", answer: "'Herhalde' ihtimal/olasılık bildirir (bitişik). 'Her halde' ise bütün durumlarda/kesinlik bildirir (ayrı)." },
  { id: 67, subject: "Türkçe", question: "Ses Olayları: 'Bekliyor' kelimesindeki ses olayı nedir?", answer: "Ünlü Daralması (Bekle-yor -> Bekliyor)" },
  { id: 68, subject: "Türkçe", question: "Ses Olayları: 'Gönlüm' kelimesindeki ses olayı nedir?", answer: "Ünlü Düşmesi (Gönül-üm -> Gönlüm)" },
  { id: 69, subject: "Türkçe", question: "Ses Olayları: 'Hissetmek' kelimesindeki ses olayı nedir?", answer: "Ünsüz Türemesi (His-etmek -> Hissetmek)" },
  { id: 70, subject: "Türkçe", question: "Dil Bilgisi: İsim çekim ekleri olan iyelik, hal, çokluk ekleri kelimenin anlamını değiştirir mi?", answer: "Değiştirmez. Çekim ekleri kelimeye sadece yeni görevler yükler." },
  { id: 71, subject: "Türkçe", question: "Bağlaç olan 'ki' ile ek olan '-ki' nasıl ayırt edilir?", answer: "Fiillerden sonra gelen 'ki' her zaman ayrı yazılır (Anladım ki). Sonuna '-ler' eki getirdiğinizde kelime anlamsızlaşıyorsa o 'ki' bağlaçtır ve ayrı yazılır." },
  { id: 72, subject: "Türkçe", question: "Anlatım Bozukluğu: 'Karşılıklı mektuplaştık.' cümlesindeki bozukluk türü nedir?", answer: "Gereksiz sözcük kullanımı ('Mektuplaşmak' zaten karşılıklı yapılan bir eylemdir)." },
  { id: 73, subject: "Türkçe", question: "Cümlede Vurgu: Fiil cümlelerinde vurgu hangi ögededir?", answer: "Yüklemden hemen önceki ögededir. (Örn: Dün kitabı [kütüphaneden] aldım. -> Dolaylı Tümleç vurgulu)" },

  // ================= MATEMATİK (10 Kart) =================
  { id: 74, subject: "Matematik", question: "Formül: 1'den n'e kadar olan ardışık tam sayıların toplam formülü nedir?", answer: "n * (n + 1) / 2" },
  { id: 75, subject: "Matematik", question: "Bölünebilme Kuralı: Bir sayının 3'e tam bölünebilmesi için kural nedir?", answer: "Sayının rakamları toplamı 3 veya 3'un katı olmalıdır." },
  { id: 76, subject: "Matematik", question: "Asal Sayılar: Asal sayılar kümesinin en küçük ve tek çift olan elemanı kaçtır?", answer: "2'dir. (2 dışında çift asal sayı yoktur, 1 asal değildir)." },
  { id: 77, subject: "Matematik", question: "Özdeşlik: İki Kare Farkı formülü (a² - b²) nasıldır?", answer: "(a - b) * (a + b)" },
  { id: 78, subject: "Matematik", question: "Faktöriyel: 0! (Sıfır Faktöriyel) kaçtır?", answer: "1'dir." },
  { id: 79, subject: "Matematik", question: "Kombinasyon: n elemanlı bir kümenin 0'lı kombinasyonu C(n,0) ile kendisi C(n,n) kaça eşittir?", answer: "1'e eşittir." },
  { id: 80, subject: "Matematik", question: "İşçi Problemleri: A işçisi x saatte, B işçisi y saatte bitiriyorsa beraber t saatte bitirme denklemi nasıldır?", answer: "(1/x + 1/y) * t = 1" },

  // ================= GÜNCEL & GENEL KÜLTÜR (15 Kart) =================
  { id: 81, subject: "Güncel", question: "Birleşmiş Milletler'in (BM) genel merkezi nerededir?", answer: "New York, ABD" },
  { id: 82, subject: "Güncel", question: "NATO'nun (Kuzey Atlantik Antlaşması Örgütü) genel merkezi nerededir?", answer: "Brüksel, Belçika" },
  { id: 83, subject: "Güncel", question: "OPEC (Petrol İhraç Eden Ülkeler Örgütü) genel merkezi nerededir?", answer: "Viyana, Avusturya (Avusturya kendisi petrol ihraç eden bir ülke olmamasına rağmen merkezi oradadır)." },
  { id: 84, subject: "Güncel", question: "Avrupa İnsan Hakları Mahkemesi (AİHM) hangi kuruma bağlıdır ve nerededir?", answer: "Avrupa Konseyi'ne bağlıdır. Merkezi Strazburg'dadır (Fransa)." },
  { id: 85, subject: "Güncel", question: "Cumhurbaşkanlığı Forsu'nda yer alan 16 yıldız neyi temsil eder?", answer: "Tarihte kurulan 16 büyük Türk Devleti'ni." },
  { id: 86, subject: "Güncel", question: "Kuzey Kıbrıs Türk Cumhuriyeti'nin (KKTC) kurucu cumhurbaşkanı kimdir?", answer: "Rauf Raif Denktaş" },
  { id: 87, subject: "Güncel", question: "İstiklal Marşı'mızın şairi Mehmet Akif Ersoy, marşı kime ithaf etmiştir?", answer: "Kahraman Türk Ordusu'na" },
  { id: 88, subject: "Güncel", question: "'Sinekli Bakkal', 'Vurun Kahpeye', 'Ateşten Gömlek' gibi Milli Mücadele dönemi eserlerinin yazarı kimdir?", answer: "Halide Edip Adıvar" },
  { id: 89, subject: "Güncel", question: "Dede Korkut Hikayelerini diğer destanlardan ayıran en belirgin edebi özellik nedir?", answer: "Nazım (şiir) ve Nesir (düz yazı) biçiminin iç içe / karışık olmasıdır." },
  { id: 90, subject: "Güncel", question: "Türkiye'nin en uzun nehri (ülke sınırları içinde doğup dökülen) hangisidir?", answer: "Kızılırmak" },
  { id: 91, subject: "Güncel", question: "2023 yılında Cumhuriyetimizin 100. yılı şerefine uzaya gönderilen ilk Türk astronotun adı nedir?", answer: "Alper Gezeravcı" },
  { id: 92, subject: "Güncel", question: "Türkiye'nin ilk yerli savaş uçağının (Milli Muharip Uçak) adı nedir?", answer: "KAAN" },
  { id: 93, subject: "Güncel", question: "UNESCO Dünya Mirası Listesi'nde yer alan 'Tarihin Sıfır Noktası' olarak bilinen Göbeklitepe hangi ilimizdedir?", answer: "Şanlıurfa" },
  { id: 94, subject: "Güncel", question: "Türkiye'nin ilk yerli ve milli otomobil projesinin kısaltması nedir?", answer: "TOGG (Türkiye'nin Otomobili Girişim Grubu)" },
  { id: 95, subject: "Güncel", question: "Dünyanın bilinen en derin noktası olan Mariana Çukuru hangi okyanustadır?", answer: "Pasifik (Büyük) Okyanusu" }
];
